version: "3"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4jdb
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins

    env_file:
      - ./neo4j.env
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: on-failure
    networks:
      - net 


  backend:
    depends_on:
      - neo4j
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend 
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8000:8000"
    networks:
      - net


  frontend:
    depends_on:
      - neo4j
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_API_URL=$VITE_BACKEND_API_URL
        - VITE_REACT_APP_SOURCES=$VITE_REACT_APP_SOURCES
        - VITE_ENV=$VITE_ENV
        - VITE_CHAT_MODES=$VITE_CHAT_MODES
        - VITE_BATCH_SIZE=$VITE_BATCH_SIZE
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net:
    driver: bridge


